### ISSUE TITLE
Use in Angular 2 app

### ISSUE THREAD

**Issue by wickeym** [jakearchibald/idb-keyval#10]
Hi,

I'm new to JS, Angular, and node.js, do you know how to add idb-keyval and use it in an Angular2 app?
I add `<script src="node_modules/idb-keyval/idb-keyval.js"></script>` to the base index.html
I add the path to the systemjs.config and to my package.json.

The issue I run into is how do I now import this in a ts module?
I tried these ways:
`import { IDBKeyVal, idbKeyVal } from 'idb-keyval';` 
`import 'idb-keyval';`
`import '../../node_modules/idb-keyval/idb-keyval.js';`
It imports it, but it never recognizes `idbKeyVal` though it is exported.

Any help would be greatly appreciated.

Sincerely,
Michael

**Comment by jakearchibald** [comment]
I'm not familiar with Angular 2's dev/build tools.

With browserify it's as simple as npm-installing `idb-keyval` then importing it.

If the build tools are causing you problems, you could just use https://github.com/jakearchibald/idb-keyval/blob/master/dist/idb-keyval-min.js on your page, then `window.idbKeyval`.

**Comment by wickeym** [comment]
Thanks, that got me on the right right track.
I import it as js in my ts file
`let idbkeyval = require('../../node_modules/idb-keyval/idb-keyval.js');`
and it works!
