### ISSUE TITLE
Key as auto incrementing numbers

### ISSUE THREAD

**Issue by abhi747** [jakearchibald/idb-keyval#102]
This is not an issue but a query.

Can we have key for `set` method as auto incrementing numbers starting from 0, as we have in native indexed DB?

**Comment by jakearchibald** [comment]
That works in IDB because it's scoped to a particular store, but idb-keyval doesn't really have the concept of a store.

I think you'd be better off with the other library https://www.npmjs.com/package/idb, where you could do:

```js
const db = await openDB('db', 1, {
  upgrade(db) {
    db.createObjectStore('entries', {
      keyPath: 'id',
      autoIncrement: true,
    });
  },
});

// Add an entry:
await db.add('entries', { foo: 'bar' });
// Get entries:
console.log(
  await db.getAll('entries'),
);
```
