### ISSUE TITLE
Publish a CHANGELOG

### ISSUE THREAD

**Issue by steelbrain** [jakearchibald/idb-keyval#109]
This is excellent package @jakearchibald! Thank you for working on it

Love the updates, I think a Changelog or release notes somewhere would make upgrades much easier for consumers.

What do you think?

**Comment by jakearchibald** [comment]
There's already https://github.com/jakearchibald/idb-keyval#updating, or do you mean something different?

**Comment by steelbrain** [comment]
I had read the README several times but not seen it, while we're on the subject, maybe a Table of Contents for the README would be nice to have too :)

As for the changelog, this is what I had in mind:

- https://github.com/nodejs/node/blob/746cc88b92c84fc72509d7fd051ee2977822f882/doc/changelogs/CHANGELOG_V15.md ( a bit hardcore )
- https://github.com/steelbrain/node-ssh/blob/ce21fa7d5f7e6ccf9a2d02833214b1d6e5b74825/CHANGELOG.md

**Comment by alexiusp** [comment]
At least some information about possible breaking changes would be nice. I'm not sure if I can easily update version of some package without breaking something. In changelog I can see what was changed and if i see something that i use changed - it means that I at least would need to do some refactoring to migrate.

**Comment by jakearchibald** [comment]
Have you seen https://github.com/jakearchibald/idb-keyval/blob/main/CHANGELOG.md?
