### ISSUE TITLE
Host on cdn

### ISSUE THREAD

**Issue by prateekbh** [jakearchibald/idb-keyval#11]
Wouldn't hosting this on a CDN make it a lot more easier for this to be used within a service worker?
As idb is the place to be accessed for stored stuff from inside a SW.

**Comment by jakearchibald** [comment]
You can do this via rawgit.com.

Eg https://cdn.rawgit.com/jakearchibald/idb-keyval/master/dist/idb-keyval-min.js.

**Comment by ctf0** [comment]
@jakearchibald can u add this solution to the readme ?
