### ISSUE TITLE
get idb-keyval function with NEXTJS app: Server Error ReferenceError: indexedDB is not defined

### ISSUE THREAD

**Issue by easinyo** [jakearchibald/idb-keyval#119]
![image](https://user-images.githubusercontent.com/34837163/120121774-5cf6a580-c173-11eb-8faa-ebeb7c9fa3b1.png)

 Version  :  "idb-keyval": "^5.0.6",

**Comment by easinyo** [comment]
Please see the console logs below:   
![image](https://user-images.githubusercontent.com/34837163/120121838-b363e400-c173-11eb-83fc-d99866756814.png)

**Comment by jakearchibald** [comment]
This library is for the browser, not NodeJS.
