### ISSUE TITLE
not working in chrome

### ISSUE THREAD

**Issue by TimWillis** [jakearchibald/idb-keyval#12]
Hi Jake, been using this for a while, but it is no longer worker in Chrome:
`idbKeyval.set('hello', 'world')
                .then(() => {
                    console.log('It worked!')
                })
                .catch(err => {
                    console.log('It failed!', err)
                });`
The promise then or catch never get called. Works in ff.  Maybe because of idb2 in chrome 58? I hadn't noticed it because I had a fallback.

**Comment by jakearchibald** [comment]
I can't recreate this issue. Here's a reduced test http://output.jsbin.com/lumica/quiet.

**Comment by TimWillis** [comment]
I think that may be the wrong test link. idbKeyval is not defined.

**Comment by jakearchibald** [comment]
Oops, sorry, I meant http://jsbin.com/huteqag/1/edit?js,console.

**Comment by TimWillis** [comment]
I'm not getting anything logged to the "console" there, I did console.log('test') to see if it would log to the console, and it did, but nothing from the idb promise. There is a screenshot, I've tried in chrome 58.0.3029.110 (64-bit) and chrome canary.  Works in FF.
![x2scrap](https://cloud.githubusercontent.com/assets/8459341/25965731/d6a7020a-3656-11e7-805f-b87eb3f9d741.png)

**Comment by TimWillis** [comment]
OK, just tested in chrome incognito and it worked. In normal Chrome I am not getting any errors and on my site I have used the clear storage for indexedDB, with still no results. Maybe this is a Chrome bug, but weird it spans on my machine both chrome and chrome canary.

**Comment by jakearchibald** [comment]
If it's spanning machines, but working fine in incognito, my hunch would be an extension is messing it up. Got any extensions installed?

**Comment by TimWillis** [comment]
That seemed like a good guess since it worked in incognito. I haven't tried
on another machine yet, just on Chrome and Chrome Canary on the same
machine. I disabled all of my extensions, probably needed to weed some out
anyway, but still no go. No errors, just never goes to then or catch.

**Comment by TimWillis** [comment]
OK, so disabled all extensions and restarted chrome with settings -> exit,
no go. Then I restarted my system and it worked... Really weird...

**Comment by TimWillis** [comment]
I think we can close this, it appears something weird with my machine. Thank you!
