### ISSUE TITLE
Error in require() in version 5.1.0

### ISSUE THREAD

**Issue by tomdrewes** [jakearchibald/idb-keyval#122]
We are building a project that uses idb-keyval via require()/browserify and we recently noticed this error that seemed to come along with the changes in 5.1.0:

Error: Cannot find module 'dist/cjs-compat/index.js' from '/Users/tdrewes/Code/serenity-clean/inara/node_modules/idb-keyval/dist/cjs-compat'

In looking at dist/cjs-compat/index.js it appears that on line 9:
var safariFix = require('dist/cjs-compat/index.js');

there may be a typo which is supposed to be referencing the source for the recent Safari bug workaround.

**Comment by jakearchibald** [comment]
Ugh, sorry, schoolboy error from me. I'll ship a fix tomorrow.

**Comment by jakearchibald** [comment]
Thank you for filing an issue on this!

**Comment by jakearchibald** [comment]
Should be fixed in 5.1.1. Let me know if there are any issues.

Closed in a2f76a455d6647b0d6639ed252b27f9190b8e720
