### ISSUE TITLE
Fix sveltekit build issues

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/idb-keyval#126]
Previously: https://github.com/jakearchibald/idb-keyval/issues/124 https://github.com/jakearchibald/idb-keyval/pull/125

The change was reverted because the libraries aren't all modules.

@philholden can you help me recreate the issue you have so I can test fixes before publishing?

**Comment by jakearchibald** [comment]
The current recommendation is to change the module files to end `.mjs`. I'm a little reluctant to do this, because:

- Requires a major version bump (which I'm not against, but only if necessary)
- Some [common configs](https://stackoverflow.com/questions/64002604/how-to-make-create-react-app-support-mjs-files-with-webpack) don't like `.mjs`

Also, isn't this a bug with vite/svelte? This library uses [conditional exports](https://nodejs.org/api/packages.html#packages_conditional_exports), so it shouldn't be trying to load a module as a cjs file or vice versa.

**Comment by philholden** [comment]
Thanks Jake. Steps to reproduce are as follows:

```
git clone git@github.com:philholden/songkit.git
cd songkit
git checkout wrangler
npm install
npm run build
```

**Comment by jakearchibald** [comment]
Hopefully this will sort it https://github.com/jakearchibald/idb-keyval/pull/129
