### ISSUE TITLE
Safari: Unhandled Promise Rejection: NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.

### ISSUE THREAD

**Issue by getflourish** [jakearchibald/idb-keyval#134]
**Issue**
```
Unhandled Promise Rejection: NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
```

**How to replicate**

macOS 11.6
Safari 15.0

When developing on localhost everything works initially. But once I deploy the code to a different domain, I tend to see this error. I don’t know what the error message is trying to tell me and how I can fix it. I have a feeling that some things are getting mixed up:

My setup:

- My HTML document embeds an iframe. 
- The iframe’s document is accessing IndexedDB. 
- While the host of the outer document can vary, the URL of the iframe is the same. 

In the web inspector under application storage, the domain of the host page is shown.

**Comment by getflourish** [comment]
I think the `onupgradeneeded` is never called for some reason, thus the store isn’t created?

<img width="786" alt="image" src="https://user-images.githubusercontent.com/183989/136359818-4816deb9-8d87-492b-88ea-45516938d21d.png">

```
function createStore(dbName, storeName) {
  const dbp = idbReady().then(() => {
    const request = indexedDB.open(dbName);
    console.log(request);
    request.onupgradeneeded = () => {
      console.log("Create store", request.result);
      request.result.createObjectStore(storeName);
    };
    console.warn("onupgradeneeded?");
    return promisifyRequest(request);
  });
  return (txMode, callback) =>
    dbp.then((db) => {
      callback(db.transaction(storeName, txMode).objectStore(storeName));
    });
}
```

**Comment by jakearchibald** [comment]
It sounds like a database of the same name had already been created on that origin, but without the object store. Does that sound likely/possible?

**Comment by getflourish** [comment]
Yes, that's what I'm seeing in Dev Tools: multiple keyval-store databases for the same domain. Is that correct or should there only ever be one?

**Comment by jakearchibald** [comment]
Only one, unless you've created many
