### ISSUE TITLE
how to use in tampermonkey script?

### ISSUE THREAD

**Issue by ChenYCL** [jakearchibald/idb-keyval#139]
hello, i'm confused use in browser .

**Comment by jakearchibald** [comment]
See https://github.com/jakearchibald/idb-keyval#all-bundles, which includes hosted versions of the script. You could even copy and paste the code into your own.

For TamperMonkey specifics, ask in their support forums, but https://www.tampermonkey.net/documentation.php?ext=dhdg#_require looks like a good start.
