### ISSUE TITLE
Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by wuweikd** [jakearchibald/idb-keyval#142]
hi：

At my sentry，I got this error：
`InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

There has been a lot of discussion on Net，But I can't reproduce it。

Can we use `try,catch` to catch It? In this way to try a few more times?

thanks

**Comment by jakearchibald** [comment]
You should get a rejected promise if transaction throws. Unfortunately without any more details there's no way I can debug this.

**Comment by bryan-hunter** [comment]
> hi：
> 
> At my sentry，I got this error： `InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`
> 
> There has been a lot of discussion on Net，But I can't reproduce it。
> 
> Can we use `try,catch` to catch It? In this way to try a few more times?
> 
> thanks

@wuweikd did you find a workaround? Hard to reproduce but happens to me as well. Wondering if just retrying solves it?

**Comment by wuweikd** [comment]
> > hi：
> > At my sentry，I got this error： `InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`
> > There has been a lot of discussion on Net，But I can't reproduce it。
> > Can we use `try,catch` to catch It? In this way to try a few more times?
> > thanks
> 
> @wuweikd did you find a workaround? Hard to reproduce but happens to me as well. Wondering if just retrying solves it?

I can't reproduce, but catch  is useful,I use catch_function  at every api
