### ISSUE TITLE
Guidance on how to treat `undefined`

### ISSUE THREAD

**Issue by EdmundsEcho** [jakearchibald/idb-keyval#147]
This is a great package.  I've used it for years and mention it to others whenever I have the chance.  Thank you.

## Observation
I'm putting this issue out more as a question.  I sometimes get a 
```
Error storing data DOMException: The object could not be cloned.
```

This could be for many values that cannot be serialized.  However, as I'm working through the problem, I thought to return to this repo to see if there is any guidance for how to treat `undefined` values (a non-serializable value).  

## Context
The error occurs  rarely.  I use the package to store and restore my redux store between reloads.  So I don't have full control for *what* and *when* data is being saved.  This said, there may be times when an `undefined` somehow slips through.  This last point seems like a contradiction because the app clearly guards for the condition prior to writing to the store, but... This is where I'm debugging.

## Suggestion
Notwithstanding, I was thinking that the documentation for `idb-keyval` might include a "best practice", or some sort of "avoid this gotcha" with `undefined` values.  It's rare, but clearly can come up.  

\- E

**Comment by jakearchibald** [comment]
`undefined` serialises fine https://static-misc-3.glitch.me/idb-keyval-test/undefined.html (see the console).

There are many types of object that don't serialise though, eg DOM elements.

**Comment by EdmundsEcho** [comment]
I haven't had to think about this until now, but does "undefined" get interpreted correctly when deserialized? i.e., as `undefined`?  I suspect the answer is yes because "I haven't had to think about this..." :)  

But, here is a quote from Mozilla that puts the "full answer" if you will, into a bit of a nuanced space:

>undefined, Functions, and Symbols are not valid JSON values. If any such values are encountered during conversion they are either omitted (when found in an object) or changed to null (when found in an array). JSON.stringify() can return undefined when passing in "pure" values like JSON.stringify(function(){}) or JSON.stringify(undefined). 

[source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

**Comment by jakearchibald** [comment]
Right but IndexedDB doesn't use JSON for serialisation, it uses [structured serialisation](https://html.spec.whatwg.org/multipage/structured-data.html#structuredserializeinternal), which specifically handles `undefined` and other types that are not well supported by JSON.

**Comment by EdmundsEcho** [comment]
That's really helpful to know.  Thank you. The inspiration for the post was a bug that was somehow introduced into my app where it was complaining of "unserializable" values.  Knowing I can eliminate `undefined` values as the issue reduces the problem space by a lot.  I have since fixed the issue but have completely forgotten what the solution was! :/... but I know it wasn't by guarding against `undefined` values! :)))
