### ISSUE TITLE
Inital keyval not being set after manually clearing db 

### ISSUE THREAD

**Issue by markwilson107** [jakearchibald/idb-keyval#149]
Not so much an issue as a heads up to those often clearing the db from application tab in developer tools. After you do so the first set or update called will not save, not likely this problem would happen ouside developemnt environment but would be good to have an Init function or something to check for this. Another solution is to set a random keyval before first set or update call.

**Comment by jakearchibald** [comment]
I'm struggling to recreate this via https://static-misc-3.glitch.me/idb-keyval-test/basic-get-set.html.

However, I can recreate something similar with "clear site data", as this breaks the connection to the database.

I'm not sure this is worth fixing, but I'm happy to be persuaded.
