### ISSUE TITLE
idbKeyval.clear() doesn't free up space in Chrome

### ISSUE THREAD

**Issue by pranksinatra** [jakearchibald/idb-keyval#15]
I've been doing some performance testing and am puzzled by the fact that `idbKeyval.clear()` does not free up temporary storage space in Chrome. In fact, if I repeatedly set and delete a key in IndexedDB using idbKeyval, Chrome DevTools reports a continual growth in storage quota usage.

Here's a simple codepen where you can add ~1kb strings to IndexedDB and then clear them all. 
https://codepen.io/pranksinatra/pen/PQweqd

I'm new to IndexedDB and browser storage quotas, so I apologize in advance if I'm missing something obvious. Thanks for pulling together such a concise library--it's been great to work with.

**Comment by drmrbrewer** [comment]
I'm not @jakearchibald but you may find the following informative: https://bugs.chromium.org/p/chromium/issues/detail?id=795735.  I too was puzzled by ever-increasing quota, and posted that bug report... in fact it seems that it's not a bug but just a reflection of what is being used behind the scenes.

**Comment by pranksinatra** [comment]
Thanks, good to know! I tweaked the demo to start storing megabytes, and sure enough, once I got high enough, clearing the database freed up some space.
