### ISSUE TITLE
Proxy objects are not supported

### ISSUE THREAD

**Issue by VirensCn** [jakearchibald/idb-keyval#150]
If value is a proxy object, an error will occur when calling set to save

![image](https://user-images.githubusercontent.com/9736815/156299876-15b3489a-7c40-4a53-a3fa-717482723f49.png)

**Comment by disarticulate** [comment]
easiest way out is ```JSON.parse(JSON.stringify))```

**Comment by jakearchibald** [comment]
Only clonable objects can be stored
