### ISSUE TITLE
`get` returns `undefined` when key is nonexistent

### ISSUE THREAD

**Issue by jonathanstanley** [jakearchibald/idb-keyval#153]
these two have different meanings:
1. key does not exist
2. key exists and value is `undefined`.

Since idb-keyval `get` returns `undefined` in both cases, the only way I can think to check the difference is something like this:
```ts
import { get, keys } from "idb-keyval";

let mykey = "hello";

((await keys()).includes(mykey)) ? console.log(get(myKey)) : console.log("404")
```

however, this causes 2 transactions for every `get`... and there may be a lot of keys.  could also use `entries`, however that would probably be worse depending on how much data has to be cloned.

Is there a better way?

**Comment by jonathanstanley** [comment]
I noticed this is the native behavior of IndexedDB API.  [MDN's recommendation](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/get):
> call the `openCursor()` method with the same key. That method provides a cursor if the record exists, and no cursor if it does not.

I see idb-keyval has `eachCursor`, but not in a way that is usable for this purpose:
https://github.com/jakearchibald/idb-keyval/blob/fdf795b9b55b417eb6ed22db9721c53877a19569/src/index.ts#L179-L183


Would it help for me to submit a PR?

**Comment by jakearchibald** [comment]
Can you give me a use-case where `undefined` vs does-not-exist matters, to help me understand the issue?

What would a solution look like?

**Comment by jonathanstanley** [comment]
# use case:

```ts
// get session from IDB (or create a session for first time visitor)
let session = idbOrGenerateNoob();

function logout(){
  session = undefined;
  setIdb(session);
}
```

in this case, `session===undefined` identifies users existing users who are not logged... so we don't want to show them all the first time user notifications. but since absent key also returns undefined, the `generateNoob` would never execute. granted there would be other ways to manage a session... example just to get a sense of the issue.

# solution:

i think something like this:
```ts
export async function getKey(idbValidKey: IdbValidKey){
 // implements https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/getKey
}

export async function strictGet(idbValidKey: IdbValidKey){
  let result = await get(idbValidKey);
  if (result === undefined) {
    if (!(await getKey(idbValidKey))) throw "nonexistent key";
  }
  return result;
}
```

**Comment by jakearchibald** [comment]
It seems like this would be much more readable if the session had a `firstLogin` boolean.

**Comment by jonathanstanley** [comment]
yes there are definitely better ways to do a session.  i was just trying to think of a case study to illustrate. anyone who comes across this is free to implement their own accommodation, or perhaps don't rely on `undefined` being stored in the indexed db.  i just didn't like seeing that `undefined` could represent two distinct states, so I thought I'd offer a PR.  but of course welcome to close as well.
