### ISSUE TITLE
Broken on Safari 15.1?

### ISSUE THREAD

**Issue by riccardoperra** [jakearchibald/idb-keyval#154]
I recently tried to integrate this library to store local data. All was working fine until I got a MacOS system and discovered that there was a big Safari bug that was "resolved".

![Schermata 2022-06-04 alle 09 20 45](https://user-images.githubusercontent.com/37072694/171989132-b891e2f1-ae82-4b69-8fb1-df248e362515.png)

![Schermata 2022-06-04 alle 09 17 10](https://user-images.githubusercontent.com/37072694/171989037-505f96a6-d4a3-4818-bcff-8468b5fe9259.png)

Here what I'm trying to do:

```typescript
const IDB_KEY = 'editor';
const idbState = await idb.get<PersistedEditorState>(IDB_KEY); // this is broken

// After everything is mounted in DOM 
idb.set(IDB_KEY, newVal) // got the same error
```

The keyval-store is correctly created, but querying or updating new documents not working. Trying this in Chrome works fine

Am I missing something?

## EDIT

It seems that in my case it's correctly working deploying the application in an https context. The error is thrown mainly in localhost. 

But there here is https://www.tldraw.com which is using this library (version 6.1.0) and I think has my same issue (just looked at the console)

![Schermata 2022-06-04 alle 09 36 36](https://user-images.githubusercontent.com/37072694/171989727-75ea22aa-18e8-410c-998e-7cf5a6e15db3.png)

**Comment by jakearchibald** [comment]
Is this issue 100% reproducible?

**Comment by riccardoperra** [comment]
Ok this is even more strange now 😄 Probably it's not related to your fix.

In the project that I'm working, I was hosting the local server to `4200` port.

I created the repo below with a small example with SolidJS. It seems that everything works if I use vite without any port configuration (default is 3000).
If I run the same command with --port=4200, idb is broken

https://github.com/riccardoperra/idb-keyval-broken-safari

### Working: port 3000
![Schermata 2022-06-04 alle 12 55 51](https://user-images.githubusercontent.com/37072694/171996049-94c9dfa1-8f12-4ac0-8a13-b6462c1c39d3.png)

### Broken: port 4200
![Schermata 2022-06-04 alle 12 56 41](https://user-images.githubusercontent.com/37072694/171996082-44aff0fe-6500-413d-a34d-8bf43ce0a9ee.png)

**Comment by jakearchibald** [comment]
Happy to re-open this if someone provides a reduced, reproducible demo of the issue.
