### ISSUE TITLE
ES module version

### ISSUE THREAD

**Issue by bennypowers** [jakearchibald/idb-keyval#17]
It would be nice if this module was available as a standard module. 

I'm happy to provide a PR

**Comment by jakearchibald** [comment]
Yeah, this sounds like a good idea. Happy to take a PR. Can you make a little build script that takes the module version and creates a non-module version?

**Comment by bennypowers** [comment]
So I'll make a PR that does the following:

* Refactors source to use ES module keywords
* Adds a build step to convert the ES module source to common js, under a `/cjs` directory.

**Comment by jakearchibald** [comment]
Sounds good. I guess edit `package.json` to point at the cjs version, but add a "module" field that points at the module.
