### ISSUE TITLE
"TypeError: idbKeyval.get is not a function"

### ISSUE THREAD

**Issue by ctf0** [jakearchibald/idb-keyval#19]
here is what i have

```js
const idbKeyval = require('idb-keyval')

getCachedResponse() {
   return idbKeyval.get('bla')
},

// somewhere else
this.getCachedResponse().then((res) => {
    console.log(res)
})
```

even when using it directly, it still give the same error
```js
idbKeyval.get('bla').then((res) => {
    console.log(res)
})
```

also is there a chance to add `catch()` as well instead of checking if the val is `undefined` ?

**Comment by jakearchibald** [comment]
It isn't clear how you're including the script. Are you trying to use this within node? Are you using some kind of bundling tool?

**Comment by ctf0** [comment]
yes, am using it with laravel mix, and here is the script it runs for watch
```
cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

**Comment by jakearchibald** [comment]
I can't recreate this issue, but I'm unfamiliar with laravel.

Here's the library being used with rollup: [code](https://glitch.com/edit/#!/idb-keyval-test?path=src/main.js:8:5), [live](https://idb-keyval-test.glitch.me/).

Here's the library being used with webpack: [code](https://glitch.com/edit/#!/idb-keyval-webpack?path=src/index.js:8:5), [live](https://idb-keyval-webpack.glitch.me/).

Both seem to be working fine.

**Comment by ctf0** [comment]
weird, still thanx

**Comment by Avien** [comment]
+1 here,
using wepback, 
`import * as idbKelval from 'idb-keyval'`

Used to work

**Comment by Avien** [comment]
changed to `import { default as idbKeyVal } from 'idb-keyval';` and it works

**Comment by ctf0** [comment]
@Avien a legend, thanx

**Comment by Avien** [comment]
![image](https://user-images.githubusercontent.com/4569044/37565468-9f04fba8-2ab2-11e8-90b4-f59dfd40f817.png)

This is the cause

**Comment by jakearchibald** [comment]
I didn't realise behaviour would change like this. I've reverted the recent module changes, and will tackle it again as a major version bump.

**Comment by jakearchibald** [comment]
3.0.0 now uses modules. 2.x doesn't.
