### ISSUE TITLE
add support to specify the store name 

### ISSUE THREAD

**Issue by ctf0** [jakearchibald/idb-keyval#21]
atm it defaults to `keyval-store`https://github.com/jakearchibald/idb-keyval/blob/1109570648855f73de57b173b666ecd5902f43a4/idb-keyval.js#L6

maybe we can have an option to pass the store name 
```js
idbKeyVal.store('something').set
idbKeyVal.store('something').get
etc..
```

**Comment by jakearchibald** [comment]
Yeah. I'll do this along with https://github.com/jakearchibald/idb-keyval/issues/22.

**Comment by jakearchibald** [comment]
Done! https://github.com/jakearchibald/idb-keyval/blob/master/README.md#custom-stores
