### ISSUE TITLE
Issue using with webpack via require()

### ISSUE THREAD

**Issue by humphd** [jakearchibald/idb-keyval#25]
```js
const idbKeyval = require('idb-keyval');
...
idbKeyval
      .get(id)
      .then(...)
```

gives me:

`Uncaught TypeError: idbKeyval.get is not a function`

Via the console I can see that the browser sees the `idbKeyval` object like this:

```
idbKeyval
{default: {...}, __esModule: true}
```

It looks like I'm hitting [this webpack issue](https://github.com/webpack/webpack/issues/4742), since I've used `require()` vs. `import`.

I'm not sure that there's anything for you to do, but FYI [this comment aimed at library authors](https://github.com/webpack/webpack/issues/4742#issuecomment-300041285).  It might be worth a documentation note for webpack users, since this seems like a common way one might end-up using your lib.

Thanks for writing it, it's really a perfect little wrapper.

**Comment by ctf0** [comment]
https://github.com/jakearchibald/idb-keyval/issues/19#issuecomment-373991468

**Comment by jakearchibald** [comment]
I've reverted the recent module changes. I'll try to do it again, but in a major version bump. Sorry about that!

**Comment by jakearchibald** [comment]
3.0.0 now uses modules. 2.x doesn't.

**Comment by ctf0** [comment]
i cant find v3 anywhere only 2.5.1, which using
```js
import { Store, set, get, del, clear } from 'idb-keyval'
new Store(
    'db-name', // db
    'store-name' // store
)
```

give error
```
_idbKeyval.Store is not a constructor
```

**Comment by jakearchibald** [comment]
The 3.0.0 thing should be fixed now.

I didn't want to add instance methods to the class since they can't tree-shake. This is why I really want the bind operator to land in JS so you can do things like:

```js
import { Store, set } from 'idb-keyval';

const customStore = new Store('custom-db-name', 'custom-store-name');
customStore::set('foo', 'bar');
```

…but it looks like the proposal is dead.

**Comment by ctf0** [comment]
okay np, btw it works correctly in v3, which npm took quite some time to reflect it, so thanx again

**Comment by jakearchibald** [comment]
That was my fault. I pushed an update to 2.x and didn't realise npm would treat that as the "latest" version.
