### ISSUE TITLE
The cool new graphics

### ISSUE THREAD

**Issue by drmrbrewer** [jakearchibald/idb-keyval#27]
Just to be super nit picky, the new graphics in the README look super-cool on npm:

![npm](https://user-images.githubusercontent.com/9009792/37718951-cbec5c9a-2d1b-11e8-9f12-dcccc31c43cb.JPG)

but not-so-super-cool on github:

![github](https://user-images.githubusercontent.com/9009792/37718960-d1b4c414-2d1b-11e8-9cd1-35e77cfe4a67.JPG)

**Comment by jakearchibald** [comment]
They seem stable now.
