### ISSUE TITLE
is it possible to have a time expiration option for stored items ?

### ISSUE THREAD

**Issue by ctf0** [jakearchibald/idb-keyval#30]

**Comment by jakearchibald** [comment]
This library is deliberately minimal, but you could build what you want on top of it. Just make your values `{value, expiryDate}`, then have an extra layer check the date.

**Comment by ctf0** [comment]
i understand ur point, but i thought maybe we can add it to the custom store declaration, this way the usage remain the same.

still thanx for ur help :trophy:
