### ISSUE TITLE
error on firefox

### ISSUE THREAD

**Issue by ctf0** [jakearchibald/idb-keyval#32]
> DOMError { name: "InvalidStateError", message: "A mutation operation was attempted on a database that did not allow mutations." }

gets triggered by
```js
import { Store, get, set, del, clear, keys } from 'idb-keyval'
const cacheStore = new Store(
   'db-name', // db
    'store-name' // store
)

let now = Date.now() // timestamp

keys(cacheStore).then((keys) => {
    keys.map((key) => {
        get(key, cacheStore).then((item) => {
            if (item.expire < now) {
                return del(item, cacheStore).then(() => {
                    console.log(`${item} removed`)
                }).catch((err) => {
                    console.warn(err)
                })
            }
        })
    })
}).catch((err) => {
    console.error(err)
})
```

the reason
```js
constructor(dbName = 'keyval-store', storeName = 'keyval') {
    this.storeName = storeName;
    this._dbp = new Promise((resolve, reject) => {
        const openreq = indexedDB.open(dbName, 1); // <<< this line
        openreq.onerror = () => reject(openreq.error);
        openreq.onsuccess = () => resolve(openreq.result);
        // First time setup: create an empty object store
        openreq.onupgradeneeded = () => {
            openreq.result.createObjectStore(storeName);
        };
    });
}
```

also for some reason i cant find any dbs under storage tab > indexedDB, so not sure if this is an issue with FF, idb, or the lib 😒 

FF: 59.0.2
OS: osx 10.11.6

**Comment by Yaffle** [comment]
is it a Private Browsing Mode?

**Comment by ctf0** [comment]
nop, i actually never use FF unless for testing, so its on the default

**Comment by jakearchibald** [comment]
@ctf0 I'm unable to recreate this. Can you create demo of the issue on jsbin.com, glitch.com or similar?

In your example code, `keys` and `cacheStore` are undefined on line 3, and I don't know what `item.exp` is supposed to be.

**Comment by ctf0** [comment]
@jakearchibald am not that familiar with browser module loaders, but here is as far as i can go with jsbin http://jsbin.com/citolepure/edit?js,console,output

**Comment by ctf0** [comment]
![test](https://user-images.githubusercontent.com/7388088/39207856-6139dcb4-4801-11e8-9ee1-6e28bda1f39f.png)

but i've tried it on windows and its working, so its probably related to mac but not sure why

**Comment by ctf0** [comment]
**Update**

http://forums.mozillazine.org/viewtopic.php?f=38&t=2791601
found the problem, you have to enable `remember history`, now it works correctly

**Comment by carcinocron** [comment]
Looks like a firefox bug prevents IndexDB from working in incognito: https://bugzilla.mozilla.org/show_bug.cgi?id=781982
