### ISSUE TITLE
import not working with webpack/npm

### ISSUE THREAD

**Issue by sarath-sasikumar** [jakearchibald/idb-keyval#34]
I am using `react` with webpack but for some reason, the import is not working.

This has been an issue for versions `3.x`.

For ex : 
```
import { Store } from 'idb-keyval'
```
I am getting the error 'Store is not a constructor'.

In the lower versions, import idbkeyval from 'idb-keyval' is working correctly.

**Comment by jakearchibald** [comment]
Can you create a reduced demo of the issue? Makes it easier for me to debug.

**Comment by sarath-sasikumar** [comment]
So it is like I have a class which is responsible for creating the store and performing all other indexed DB operations.

```
import { Store } from 'idb-keyval';

class IndexedDB {

static createStore()
 const store=new Store('test','test-store');
}
}
```
Now when I call this class from a react component with IndexedDB.createStore() I am encountered with the error : 'Store is not a constructor'

Similar error is encountered when I call the get and set functions as well.

BUT when I roll backed to the 2.X version and imported like
```
import idbKeyval from 'idb-keyval';

```

and used idbKeyval.get(), then it is working as expected.

**Comment by jakearchibald** [comment]
By reduced demo I mean something that I can run on my machine and see the same error you're seeing. So that means including your package.json and configs.

https://css-tricks.com/reduced-test-cases/ is a good article about reduced test cases, although it's kinda font-end focused.

**Comment by zackad** [comment]
I've setup a project at https://github.com/zackad/idb-keyval-failed-to-minify-with-webpack to show the problem I'm facing.

**Comment by sarath-sasikumar** [comment]
Any update on this ?

**Comment by jakearchibald** [comment]
This isn't a webpack or npm issue, it's a bug in create react app. https://github.com/facebook/create-react-app/issues/4820
