### ISSUE TITLE
how to refresh (updates) the data in the indexedDB ?

### ISSUE THREAD

**Issue by johnqiuwan** [jakearchibald/idb-keyval#38]
I am testing this awesome library with my project. 

Just a quick question, how can I auto-update the data in the indexedDB (set maxAge etc) ? 

As you know, when the server data get updates, I need to refresh the data in the indexedDB to make the data consistent.

Thank you in advance!

**Comment by jakearchibald** [comment]
Nothing changes in indexeddb unless you tell it to, so use https://github.com/jakearchibald/idb-keyval/blob/master/README.md#set when you want to set data.

**Comment by johnqiuwan** [comment]
Thank you for your reply.

However, how could we update the version of the indexedDB to refresh the data in client side?

**Comment by jakearchibald** [comment]
Why do you need to update the version? You should only update the version if you need to make a schema change, which is kinda irrelevant in a keyval store.
