### ISSUE TITLE
Import { get } from 'idb-keyval' Unexpected Token

### ISSUE THREAD

**Issue by DanJ210** [jakearchibald/idb-keyval#39]
I don't get it. I'm not sure how the imports work. But I installed idb-keyval by updating my package.json and I'm told that the brace for the `{get}` is an unexpected token. I tried `npm install idb-keyval` but am told no such file or directory exists. I did `npm install -g idb-keyval` successfully but still doesn't change the brace issue. I don't get how this is supposed to work.

If I just wanted to download the script itself then how would I load it into my serviceworker for use?

![serviceworker](https://user-images.githubusercontent.com/16159685/42067590-dd268c28-7b14-11e8-9da5-0ad92d4f32ae.PNG)

**Comment by jakearchibald** [comment]
See https://developers.google.com/web/fundamentals/primers/modules and https://jakearchibald.com/2017/es-modules-in-browsers/ to learn more about modules in browsers.

Modules aren't supported in workers yet. Also, browsers don't support 'bare' module specifiers (where would it get the module from?).

You might be interested in one of the other distributions https://github.com/jakearchibald/idb-keyval/blob/master/README.md#via-script.

**Comment by jakearchibald** [comment]
Download https://github.com/jakearchibald/idb-keyval/blob/master/dist/idb-keyval-iife.min.js and place it somewhere your web server can serve it, then in your service worker script:

```js
importScripts('url-to-the-above-file');
```

**Comment by DanJ210** [comment]
Thank you for the helpful responses @jakearchibald. I suppose I need to understand how importing of modules work. But if I get the source file onto my web server and then do the `importScripts` is that technically the same as importing the module? I could then use the object that's exported from the file?

The workaround so far is that I've just added the code to my file for the moment. Except I'm unable to store a request object in the keyval database so I might not be able to do what I'm wanting to do.

**Comment by drmrbrewer** [comment]
@jakearchibald I too am using `idb-keyval` inside a service worker script.  

At the moment I'm using an old version of `idb-keyval`, and importing the `idb-keyval` script into my service worker via the following:

    self.importScripts('./lib/idb-keyval.min.js');

then accessing functions via e.g.:

    idbKeyval.keys().then(/*blah*/)

Is it the same with the newer "modular" version of `idb-keyval`, since modules are not supported in workers?

i.e. use `idbKeyval.keys().then(/*blah*/)` (as before) rather than `keys().then(/*blah*/)` (as per the new module format)?

**Comment by drmrbrewer** [comment]
OK I just answered my own question.  Seems like that is indeed the case... it's pretty much "as before", i.e. reference the methods via `idbKeyval` rather than directly, with the only change (for me) being to replace `idbKeyval.delete()` with `idbKeyval.del()`.
