### ISSUE TITLE
AbortError: Version change transaction was aborted in upgradeneeded event handler

### ISSUE THREAD

**Issue by micahjon** [jakearchibald/idb-keyval#41]
First of all, thanks for this tiny, reliable library! We've been using it in production at [BeFunky](https://www.befunky.com/), and I've been working on replicating and handling IndexedDB startup issues across browsers (e.g. private modes, QuotaExceeded, etc.).

However, I've been unable to replicate (or understand) this frequently occurring error in Chrome/Opera:

**AbortError**: _Version change transaction was aborted in upgradeneeded event handler._

This error rejects the `_dbp` Promise in the `Store` constructor. I've been reaching into the internals a bit so that I can handle startup errors before calling methods on the `Store`.

My IndexedDB wrapper class looks like this:

```js
this.idbKeyval = require('idb-keyval');

try {
    this.idbKeyvalStore = new this.idbKeyval.Store;
}
catch (error) {
    // Handle an synchronous errors that won't be handled as events by the request.onerror handler
    // For instance, window.indexedDB is undefined in Microsoft Edge during Private Browsing
    return handleError('new idbKeyval.Store failed', error);
}

this.idbKeyvalStore._dbp.then(
    
    // Database successfully opened. Start processing queued requests.
    () => resolve(true),
    
    // Unable to open database
    // The error below is the AbortError mentioned above
    error => handleError('indexedDB.open failed', error)
);
```

In this case, `_dbp.then()` rejects with the `AbortError`.

Just wondered if you'd seen this sort of thing before and could point me in the right direction. If this is outside of the scope of this repo, I totally understand. Thanks!

**Comment by jakearchibald** [comment]
Please reopen if you're still seeing this (with a reproduction if you have one)
