### ISSUE TITLE
Compatibility with React

### ISSUE THREAD

**Issue by Saphyel** [jakearchibald/idb-keyval#43]
I'd like to use this project on my react app, but fails when tries to minify. [reason](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify)

Any recommendation or plan to fix it?

Thanks I really like the project!!!

**Comment by jakearchibald** [comment]
I've used this library in React projects before without problem, so the issue is more to do with the build setup of create-react-app. I'm not familiar with that project, but I've asked for guidance. https://github.com/facebook/create-react-app/issues/4820

**Comment by Saphyel** [comment]
You can use the library without problems.. but the issue comes when you try to "build" it for production  because it returns an error trying to minify some files.

I appreciate you take your time looking into this thanks!!!

**Comment by Saphyel** [comment]
Saw it! thanks

**Comment by Saphyel** [comment]
@GusRuss89 you have to update your react-scripts to the version 2. Please take a look to the issue linked for more details/questions.
