### ISSUE TITLE
Configuration for webpack

### ISSUE THREAD

**Issue by Saphyel** [jakearchibald/idb-keyval#48]
I'm trying to use this project for React... I've been debugging trying to figure out why stop working from one version to the next one and I found out that is related with webpack.
Not sure if this is the right because is the integration what is failing :/
but this is the error:
`idb_keyval__WEBPACK_IMPORTED_MODULE_0__.Store is not a constructor`

the code needed to see the error when compiles the code webpack: 
```
const customStore = new Store('db', 'name');
```

**Comment by jakearchibald** [comment]
Can you create a reduced example of the issue?

**Comment by Saphyel** [comment]
Somehow now is working... I didn't change a line of code in all this time... so I guess some package fixed it
