### ISSUE TITLE
conflict with other lib that use "Store" as default export

### ISSUE THREAD

**Issue by ctf0** [jakearchibald/idb-keyval#49]
vuex also use the same word `store` which when installing idb we will get an error of `reserved import word`, so as a solution we could change the class name to something like `idb`
https://github.com/jakearchibald/idb-keyval/blob/d52c361c63356afc672e2fee531e4509cc6c7434/idb-keyval.ts#L1

this way we make sure it doesn't conflict with any other lib of the same nature, this probably means the version will need to be bumped as this will add a breaking change for anyone using the custom store https://github.com/jakearchibald/idb-keyval#custom-stores

**Comment by jakearchibald** [comment]
```js
import { Store as KeyvalStore } from 'idb-keyval';
```

**Comment by ctf0** [comment]
i tried with vuex and it didnt work, for idb am not sure if its possible, here is my current import
```js
import {Store, get, set, del, clear, keys} from 'idb-keyval'
```

and the error
```
Uncaught SyntaxError: Unexpected reserved word 
```

**Comment by jakearchibald** [comment]
Are you getting this error at build time, or in the browser?

**Comment by ctf0** [comment]
in browser and here is the update import
```
import { Store as KeyvalStore, get, set, del, clear, keys } from 'idb-keyval';
```

**Comment by jakearchibald** [comment]
https://jsbin.com/xevuvu/2/edit?html,console works fine here.

Can you create a reduced example of the error you're seeing?

**Comment by ctf0** [comment]
sure, give me a min

**Comment by ctf0** [comment]
sorry for the delay, i cant reproduce it with a plain vue-cli either & i cant pin-point the exact issue with the main project where the error is showing :( , still i apologist for the disturbance
