### ISSUE TITLE
Unexpected token: name (Store)

### ISSUE THREAD

**Issue by devalexandre** [jakearchibald/idb-keyval#51]
when I try do bundle in preact display it

✖ ERROR bundle.1c924.js from UglifyJs
Unexpected token: name (Store) [../node_modules/idb-keyval/dist/idb-keyval.mjs:1,0][bundle.1c924.js:5809,6]

**Comment by jakearchibald** [comment]
This is a bug with uglify, not the library. Use something more modern like terserjs.
