### ISSUE TITLE
Potential transaction ordering issue?

### ISSUE THREAD

**Issue by stkao05** [jakearchibald/idb-keyval#52]
Base on the IDB spec, The ordering of the transaction creation determines how the ordering of end  result being written

> If multiple read/write transactions are attempting to access the same object store (i.e. if they have overlapping scope), the transaction that was created first must be the transaction which gets access to the object store first. Due to the requirements in the previous paragraph, this also means that it is the only transaction which has access to the object store until the transaction is finished.

The specific part of the code in the idb-keyval that I am not sure of is 

```
  _withIDBStore(type: IDBTransactionMode, callback: ((store: IDBObjectStore) => void)): Promise<void> {
    return this._dbp.then(db => new Promise<void>((resolve, reject) => {
  
      const transaction = db.transaction(this.storeName, type);
      ...
  }
```

Here the transaction is created inside the `then()` clause of the Promise and there isn't a guarantee ordering of how each Promise is resolved.  If that is true, the implication is that when the following code runs

```
import { set } from 'idb-keyval';
set('foo', 1);
set('foo', 2);
```

It is not guaranteed that after two `set()` call resolves, `2` will be persisted. 

(That said I could be wrong here... Please correct me if I do since you have a much expert knowledge on JavaScript event loop model works :))

**Comment by jakearchibald** [comment]
```js
set('foo', 1);
set('foo', 2);
```

The above will happen in order. The first will queue a `readonly` transaction, as does the second. Read-only transactions are exclusive locks, so the second will queue behind the first.
