### ISSUE TITLE
indexedDB on Edge doesn't support putting null values

### ISSUE THREAD

**Issue by dgeibi** [jakearchibald/idb-keyval#54]
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/106663/

```js
store.put("item", null)
// Invalid argument.
```

solution:
[cast null to undefined before storing value](https://github.com/localForage/localForage/pull/761)

**Comment by jakearchibald** [comment]
I've added a note about this 98380a8d965709d7f4fdcd42211e584322ee7fab
