### ISSUE TITLE
atomic `update`

### ISSUE THREAD

**Issue by wmhilton** [jakearchibald/idb-keyval#56]
Off-topic, but I think this would work as an addition to idb-keyval:

```ts
export function update(key: IDBValidKey, updater: (val: any) => any, store = getDefaultStore()): Promise<void> {
  return store._withIDBStore('readwrite', store => {
    const req = store.get(key);
    req.onsuccess = () => {
      store.put(updater(req.result), key);
    };
  });
}
```

_Originally posted by @jakearchibald in https://github.com/WICG/kv-storage/issues/56#issuecomment-472037556_

---

So I've been using that. It works! Would you consider adding it officially?

**Comment by wmhilton** [comment]
@jakearchibald any interest in this?

**Comment by jakearchibald** [comment]
I'm not desperate to add this, but I think I'd add it in the next version.

**Comment by jakearchibald** [comment]
I've added this to the new version https://github.com/jakearchibald/idb-keyval/pull/94/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R113
