### ISSUE TITLE
Arrow function not supported on older browsers with Parcel

### ISSUE THREAD

**Issue by remko** [jakearchibald/idb-keyval#59]
The dist version of idb-keyval uses arrow functions. However, Parcel doesn't transpile code in node_modules, so as a result, idb-keyval doesn't work in a parcel project for browsers such as IE11. 

Would it be possible to provide a version in dist that only uses ES5 syntax?

**Comment by jakearchibald** [comment]
This seems the wrong way around to me. It isn't for me to decide what your transpilation target should be.

Any idea why Parcel chose this approach?

**Comment by jakearchibald** [comment]
But yeah, I'll made an es5 build (I'll also accept a PR if you want it faster)

**Comment by remko** [comment]
Not disagreeing.

If I would have to take an educated guess: running all of `node_modules` through babel has a performance impact, and you can't pick because Parcel is zero-configuration. I think the common assumption is that node_modules has a package that at least parses (almost) anywhere. (and this package is the first I ran into that failed this, hence my question).
