### ISSUE TITLE
Set Fails on Safari with no error

### ISSUE THREAD

**Issue by Mihyar-30614** [jakearchibald/idb-keyval#62]
Using Safari on IOS idbKeyval.set() fails with no error returned

**Comment by jakearchibald** [comment]
Here's a small demo that works fine in Safari: https://static-misc.glitch.me/idb-keyval-test/.

Can you create a reduced demo that fails in the way you're seeing it fail?

**Comment by Mihyar-30614** [comment]
`idbKeyval.set(id, {
			body: "",
			blob: blob,
			headers: myHeadersArray
		})
		.then(() => {
			console.log("idbKeyval successfully added: " + id);
		})
		.catch(err => {
			console.log("idbKeyval failed: " + id + "Reason: " + err);
		})`

trying to save .gif file from caches using Safari on IPad

**Comment by jakearchibald** [comment]
That isn't a demo. Please use something like glitch.com, github pages, or whatever, to create a page that I can run which demonstrates the error you're seeing.

**Comment by jakearchibald** [comment]
You can't store blobs in Safari on iOS. Convert it to an arraybuffer instead.
