### ISSUE TITLE
Ability to close the IndexedDB connection

### ISSUE THREAD

**Issue by nolanlawson** [jakearchibald/idb-keyval#64]
First off, love this little library; it saves me a lot of time. Thanks for writing it. :)

According to Google's [Page Lifecycle API best practices](https://developers.google.com/web/updates/2018/07/page-lifecycle-api#developer-recommendations-for-each-state) it's a good idea to close any IDB connections when transitioning to a "frozen" state. It would be convenient if this library provided a way to do this.

**Comment by jakearchibald** [comment]
I couldn't think of a nice way to do this. Once you need `close()`, you need a way to reopen, and need to handle other tabs that may be blocking etc etc. At that point, you're much better off using https://github.com/jakearchibald/idb/ which gives you all the callbacks you need.
