### ISSUE TITLE
Batched set

### ISSUE THREAD

**Issue by andyjessop** [jakearchibald/idb-keyval#66]
Would you accept a pull request to extend the API ever so slightly? The idea would be to allow batched setting of data with a `setMany`:

```
async function setMany(entries): {
  return store._withIDBStore('readwrite', store => {
    entries.forEach(entry => {
      store.put(entry, entry.f);
    });
  });
}
```
Testing locally, this allows for much faster batch processing.

**Comment by jakearchibald** [comment]
I don't get the `.f` part.

**Comment by andyjessop** [comment]
Oh sorry, that was specific to my use-case.

**Comment by jakearchibald** [comment]
Adding batched stuff doesn't seem unreasonable… but rather than adding a load of extra methods, maybe we should just expose `_withIDBStore`? With a friendlier name maybe.

**Comment by andyjessop** [comment]
I think that would make sense. It's very similar to what I have at the moment, an `idb-keyval-extensions` file, and it feels ergonomic enough.

**Comment by jakearchibald** [comment]
Next version has `setMany` https://github.com/jakearchibald/idb-keyval/pull/94/files#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R74
