### ISSUE TITLE
In webpack4, when use babel to translate it, "exports is not defined" error happened

### ISSUE THREAD

**Issue by tomwang1013** [jakearchibald/idb-keyval#67]
Because this lib use class in dist code, it can't work in IE 11, so we need to translate it with babel like:
```javascript
// webpack config
{
        test: /\.m?js$/,
        use: 'babel-loader',
        exclude: file => {
          return /node_modules/.test(file)  && !/idb-keyval/.test(file);
        }
      },
```
But webpack compiling failed with:
![image](https://user-images.githubusercontent.com/1826003/58794339-8cc54e00-862a-11e9-9884-efdbb50f304f.png)

**Comment by tomwang1013** [comment]
It seems that webpack can't compile the mjs file. I don't know if it is webpack's issue or this lib's issue.

**Comment by jakearchibald** [comment]
Yeah, I've encountered this elsewhere. I'll change it to js.

**Comment by ormasoftchile** [comment]
Hi, Jake. I am seeing a possibly related issue when using the library on an aurelia project I am building. The bundler is called alameda.
I added idb-keyval with:

`yarn add idb-keyval`

When building, this error message appears:

> { Error: File not found with singular glob: /Users/cormazab/Projects/aurelia-alameda/node_modules/idb-keyval/dist/idb-keyval.mjs.js (if this was purposeful, use `allowEmpty` option)
>     at Glob.<anonymous> (/Users/cormazab/Projects/aurelia-alameda/node_modules/glob-stream/readable.js:84:17)
>     at Object.onceWrapper (events.js:286:20)
>     at Glob.emit (events.js:198:13)
>     at Glob.EventEmitter.emit (domain.js:448:20)
>     at Glob._finish (/Users/cormazab/Projects/aurelia-alameda/node_modules/glob/glob.js:197:8)
>     at done (/Users/cormazab/Projects/aurelia-alameda/node_modules/glob/glob.js:182:14)
>     at Glob._processSimple2 (/Users/cormazab/Projects/aurelia-alameda/node_modules/glob/glob.js:688:12)
>     at /Users/cormazab/Projects/aurelia-alameda/node_modules/glob/glob.js:676:10
>     at Glob._stat2 (/Users/cormazab/Projects/aurelia-alameda/node_modules/glob/glob.js:772:12)
>     at lstatcb_ (/Users/cormazab/Projects/aurelia-alameda/node_modules/glob/glob.js:764:12)
> 

I went to the node_modules/idb-keyval/dist folder, and changed the filename of idb-keyval.mjs to idb-keyval.mjs.js and then the error disappeared.

This is what I can report. Thanks for this excellent piece of software.

**Comment by whaaaley** [comment]
This is also a problem with the TypeScript compiler with the `--allowJs` flag as well as `esbuild`. Importing the `.mjs` file directly solves both problems for me.

**Comment by jakearchibald** [comment]
Version 4 uses `.js` https://github.com/jakearchibald/idb-keyval/pull/94
