### ISSUE TITLE
Add deleteDatabase function

### ISSUE THREAD

**Issue by deiu** [jakearchibald/idb-keyval#72]
Hi,

It would be really great to add a new function that completely deletes a custom database if it was used. Basically expose `indexedDB.deleteDatabase(customDB)` and `dbInstance.deleteObjectStore(name)`.

Something along the lines of:

```js
import { Store, set } from 'idb-keyval';

const custom = new Store('custom-db-name', 'custom-store-name')
custom.deleteDatabase()

```

**Comment by jakearchibald** [comment]
Isn't `indexedDB.deleteDatabase(customDB)` pretty easy to use?

**Comment by deiu** [comment]
Technically it is, but since this `idb-keyval` is a wrapper, I thought it could expose the `deleteDatabase()` method. :)

**Comment by jakearchibald** [comment]
I don't think we need a wrapper for `indexedDB.deleteDatabase`. I don't see the benefit.

**Comment by jvalente** [comment]
Hi @jakearchibald! Arguably, to delete a database within the context of `idb-keyval` is a bit more complex. The connection to the database needs to be halted prior to such action and to do that outside of the dependency does look a bit awkward, imo.
It could be justified to perform this within the wrapper. What do you think?

**Comment by EdmundsEcho** [comment]
I've been using this db for a few years now. Thank you!!

I was looking into using multiple instances (custom db). With that, a robust way to delete a db instance from the user-agent. My first go was to use a combination of keys and delMany. 

All this to say, despite having read the docs beforehand, I completely missed the idea of calling indexdb directly. It may be a useful addition to the docs: how to clean-up, remove an instance.
