### ISSUE TITLE
DataError: Failed to write blobs.

### ISSUE THREAD

**Issue by mcorner** [jakearchibald/idb-keyval#76]
We are getting this error when writing from some of our users (all Chrome).  Resetting their DB fixes it, but that isn't a great solution.  Restarting the browser etc doesn't work, it is permanently broken.

The only reference I can find to this error is here: https://github.com/localForage/localForage/issues/788

And indeed we switched to using idb-keyval based on the recommendation in that github issue, but it happens with idb-keyval as well.

I don't think this is an issue with idb-keyval, but I am hoping someone might have some insight into where this comes from.

**Comment by mcorner** [comment]
We also see QuotaExceededError even though we are way, way under the quota according to:

```    
if ('storage' in navigator && 'estimate' in navigator.storage) {
  navigator.storage.estimate().then(({usage, quota}) => {
    log(ual`Storage using ${usage} out of ${quota} bytes.`);
  });
}
```

We are pretty befuddled as to why this happens.

**Comment by jakearchibald** [comment]
This seems like a browser bug rather than anything to do with this library. Please file it with the browser's tracker, which is crbug.com in the case of Chrome.
