### ISSUE TITLE
A way to get everything in the store, similar to idb getAll()

### ISSUE THREAD

**Issue by jhwheeler** [jakearchibald/idb-keyval#79]
First off, great package! It's been really easy to work with.

While I began configuring everything, I noticed I wanted to get everything in the store. I see idb has a `getAll` function; is there something similar in this package? 

The workaround I thought of using is to iterate over `keys` and do a `get` on each key, but I feel like there could be a much more performant way to do this with something like idb's `getAll`.

Thanks in advance!

**Comment by jakearchibald** [comment]
I agree there should be a way to do this, but there isn't right now.

In the meantime, https://github.com/jakearchibald/idb/blob/master/README.md might be more useful to you.

**Comment by jhwheeler** [comment]
@jakearchibald  Thanks for the quick reply! I think I'll stick to idb-keyval for now, since other than this there isn't much else I need from idb (plus, 500B is too hard to pass up haha).

BTW I'd love to do a PR for this if you could give me a few pointers on where to start. I was reading through the `getMethod` function in iddb/index.js and figured that would be a good beginning, but would appreciate any input from you. Thank you!

**Comment by jakearchibald** [comment]
I've added `entries()` to 4.0.0 (releasing soon)
