### ISSUE TITLE
discussion: Why idb-keyval is an IIFE instead of being a simple function?

### ISSUE THREAD

**Issue by NoNameProvided** [jakearchibald/idb-keyval#8]
Does it have any special reason why _idb-keyval_ is implemented as an immediately executed function and gets attached to the global scope? Why doesn't it a function which returns an object when being called? 

Exposing it as a function would allow a small improvement: allowing to specify the datastore name when initializing the lib.

**Comment by jakearchibald** [comment]
I was trying to keep it as close to localstorage as possible.
