### ISSUE TITLE
Error swallowed: "The serialized keys and/or value are too large"

### ISSUE THREAD

**Issue by knpwrs** [jakearchibald/idb-keyval#83]
`onabort` and `onerror` are set to the same handler which rejects the promise with the value of `transaction.error`. Unfortunately, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/IDBTransaction/error), this property is always `null` in the case of an abort call. I had to replace these handlers with my own in order to see that I was running into an error that says, "DOMException: The serialized keys and/or value are too large."

![image](https://user-images.githubusercontent.com/174864/81508353-9a229800-92d1-11ea-87d4-6508e356ac5c.png)

**Comment by jakearchibald** [comment]
I _think_ I know what the issue is here, but can you create a minimal reproduction of the issue so I can be sure? I'll also incorporate it into tests to avoid regressions in future.

**Comment by mcorner** [comment]
We are seeing null exceptions during get calls on Chrome.  I am thinking it might be related to this.  It is somewhat rare (I haven't been able to reproduce it myself), but if you @knpwrs  have a potential pull or even just a code snippet, we can fork locally to try and recover the underlying error.  Thanks.

**Comment by mcorner** [comment]
Something like this:

```
      transaction.onerror = () => reject(transaction.error);
      transaction.onabort = (event) => reject((<IDBRequest>event.target).error);
```

**Comment by mcorner** [comment]
Unfortunately, even with that change, I have certain users that randomly have get throw a null exception with no explanation whatsoever.  I even put in a retry (5 times with a 1 second pause) and I still get exceptions.  I can't replicate it locally, and it is driving me a bit bonkers.  All Chrome users.

**Comment by jakearchibald** [comment]
Please reopen if you find a reliable way to reproduce the error (even if it needs to be run in a tight loop or whatever).
