### ISSUE TITLE
Usage in Typescript

### ISSUE THREAD

**Issue by nero120** [jakearchibald/idb-keyval#84]
I'd like to use this library in a a TS project, however importing like:

```
import { set } from 'idb-keyval';
```

results in an TS compile error:

```
TS2307: Cannot find module 'idb-keyval'.
```

I'm guessing this is because TS does not support importing from .mjs files. Do you have any suggestions on the best approach to consume this library?

**Comment by jakearchibald** [comment]
https://github.com/jakearchibald/idb-keyval-build-example - this just works for me.

If you're seeing a problem I'm not, please create a _reduced_ example of the problem so I can debug it.

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nero120** [comment]
@jakearchibald thank you for your quick response and example, as a result I discovered the problem was that I was setting `module` in my `tsconfig.json` to "ES2015". I'm not exactly sure why, but using any other value apart from "CommonJS" will result in the compiler being unable to find your module. Any idea why that is?

**Comment by jakearchibald** [comment]
I use:

```
"module": "ESNext",
"moduleResolution": "node"
```

"classic" module resolution is deprecated.
