### ISSUE TITLE
is getAllKeys sufficiently implemented by now?

### ISSUE THREAD

**Issue by v-python** [jakearchibald/idb-keyval#85]
Seems like getAllKeys is implemented enough places, and long enough ago that keys could be rewritten to use it now?

**Comment by jakearchibald** [comment]
Hm, maybe. I've generally kept the browser support pretty wide here. I'll look at the tradeoffs for the next major version.

**Comment by v-python** [comment]
Another option might be to test for getAllKeys, and use it if available.

**Comment by jakearchibald** [comment]
I'd rather keep one way of doing things, rather than branch for different browsers. https://github.com/jakearchibald/idb/ gives you more control here, if you need it.
