### ISSUE TITLE
Specify db version in constructor

### ISSUE THREAD

**Issue by devdpontes** [jakearchibald/idb-keyval#88]
Hi,

Thanks for creating this tiny library, it's great.

I've started using it to replace an existing more bloated solution in a product I'm working on, but because of that, I have to integrate it with an existing db already on the client. Since the existing version is different, it fails to initialise. Could we get another parameter in the constructor to specify the version? I don't mind creating a PR if you're ok with that change.

**Comment by jakearchibald** [comment]
Take a look at https://github.com/jakearchibald/idb-keyval/issues/80 - would this solve the issue?

**Comment by devdpontes** [comment]
I tried your solution but I get an error when trying to use `set`: `store._withIDBStore is not a function`, which makes sense, since the store being provided doesn't have `_withIDBStore `. Tbh, at this stage, it's almost replicating the whole library, so if adding the extra parameter for the version is something you're not keen on or don't think it should be provided, I can find another way (maybe fork or take only the bits I need).

**Comment by jakearchibald** [comment]
How did you try the solution? It isn't implemented yet, it's a proposal for the next version.

If you need more control over the database, there's this library: https://github.com/jakearchibald/idb/#keyval-store

**Comment by devdpontes** [comment]
> How did you try the solution? It isn't implemented yet, it's a proposal for the next version.

Apologies, I completely missed that point.

I really only need simple `set` and `get` features, which this was perfect for. Thanks for the help and prompt replies! 🙂
