### ISSUE TITLE
IE compatibility

### ISSUE THREAD

**Issue by timtribers** [jakearchibald/idb-keyval#89]
Thanks for making this library @jakearchibald .

I just want to clarify, your README seems to suggest that "dist/idb-keyval-iife-compat.min.js" ought to work in IE 10+, can that really be right?  The code uses Promise and .then() which are not supported in any version of IE (https://caniuse.com/promises).

Can you provide an example of how you would expect to get an item in IE?

**Comment by jakearchibald** [comment]
You'll need to include a promise polyfill

**Comment by timtribers** [comment]
ok @jakearchibald , thanks.
