### ISSUE TITLE
Multiple tables

### ISSUE THREAD

**Issue by bhollis** [jakearchibald/idb-keyval#9]
I love idb-keyval - it's perfect for almost all my simple IndexedDB needs, with such a nice API. Thank you!

One thing that I sometimes thing would be nice is if I could make different instances of idbKeyval that are backed by different tables, just so I can separate my data out. Right now I just prefix my keys uniquely and it works out, but that feels a bit messy, and makes dropping all items of a certain category tough (instead of dropping the whole table, I have to iterate the keys and check prefixes). What do you think?

**Comment by jakearchibald** [comment]
Have you seen https://www.npmjs.com/package/idb? There's an example that lets you recreate a key-val store there.

**Comment by bhollis** [comment]
Yup, I should probably just do that, but it feels kind of icky to have to copy that code into my project. 

-Ben
