### ISSUE TITLE
4.x regression: no exported type for StoreGetter

### ISSUE THREAD

**Issue by dbjorge** [jakearchibald/idb-keyval#96]
We consume `idb-keyval` in a TypeScript project that uses custom stores. In 3.x, our usage looked something like:

```
import { get, Store } from 'idb-keyval';
export class IndexedDBApi {
    constructor(private readonly store: Store) {}
    public async get<T>(key: string): Promise<T> {
        return await get<T>(key, this.store);
    }
    // etc
}
```

In 4.x, the `Store` type has been removed; `get`/`set`/etc now accept a type that is inferred to be equivalent to the equivalent of `StoreGetter`, but the library doesn't export the `StoreGetter` type, and even if it did, it's awkward to discover the type since it isn't documented and `createStore` isn't implemented in terms of it.

We can use `Return<typeof createStore>` or `Parameters<typeof get>[1]` as a workaround, but these are less ergonomic than just being able to use an exported type like 3.x allowed.

It would be easier to use the library from TypeScript if:
* the `StoreGetter` type were exported
* `createStore` specified `StoreGetter` as its return type
* exported functions which accept an optional `StoreGetter` (`get`/`set`/etc) explicitly specified the type of that parameter explicitly in terms of `StoreGetter` (eg, as `customStore?: StoreGetter = defaultGetStore()`)

**Comment by jakearchibald** [comment]
> it's awkward to discover the type since it isn't documented

fwiw, custom store stuff is documented at https://github.com/jakearchibald/idb-keyval/blob/master/custom-stores.md.

I'll get a PR together for the rest…

**Comment by jakearchibald** [comment]
Do the changes in 1af0a00 resolve this for you?

**Comment by dbjorge** [comment]
Yes, still looks good to me! Thanks again for resolving it so quickly

**Comment by jakearchibald** [comment]
Brilliant!
