### ISSUE TITLE
the dell by key function doesn't work

### ISSUE THREAD

**Issue by dodicandra** [jakearchibald/idb-keyval#98]
I tried to remove one of the idb from the wrong key, but the dell function doesn't work

```javascript
const onSesion = useCallback(async () => {
    await del('live-chat');
    localStorage.clear();
    dispatch({type: 'LOGOUT', payload: null});
  }, [dispatch]);
```

**Comment by jakearchibald** [comment]
https://codesandbox.io/s/throbbing-moon-gcusw?file=/index.html - seems to work fine. There are also tests for this method which pass https://github.com/jakearchibald/idb-keyval/blob/master/test/index.ts#L156.

Please reopen with a minimal reproducible demo of the issue. Eg, https://codesandbox.io/s/throbbing-moon-gcusw?file=/index.html is a minimal reproduction that shows it working. The reproduction should not include things like React unless React is required to cause the issue.
